sudo: false

# os:
#   - osx
#   - linux
#   - windows

language: node_js

node_js:
  - lts/*

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn lint
  - yarn test
